### ISSUE TITLE
Compilation error with latest nightly

### ISSUE THREAD

**Issue by abusch** [Twinklebear/light_arena#1]
`light_arena` fails to compile with the latest nightly:

```
error[E0200]: the trait `std::ops::Place<T>` requires an `unsafe impl` declaration
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/light_arena-0.1.1/src/lib.rs:246:1
    |
246 | / impl<'a, T: 'a + Sized + Copy> Place<T> for AllocatorPlacer<'a, T> {
247 | |     fn pointer(&mut self) -> *mut T {
248 | |         self.ptr as *mut T
249 | |     }
250 | | }
    | |_^
```

It looks like implementing the `Place` trait is now considered unsafe. Edit: here's the relevant PR: https://github.com/rust-lang/rust/pull/47299

I'll be happy to open a PR as soon as I can upgrade to a version of nightly that has RLS...

**Comment by Twinklebear** [comment]
Thanks for the report! This is fixed in 23700f0bdc9fbf43ad4337382b418273947d162d , I'll publish a point release in just a moment.
